function sma = stateMatrix(iTrial)
global BpodSystem
global TaskParameters

LeftValveTime  = GetValveTimes(BpodSystem.Data.Custom.RewardMagnitude(iTrial,1), 1);
RightValveTime  = GetValveTimes(BpodSystem.Data.Custom.RewardMagnitude(iTrial,2), 3);

if BpodSystem.Data.Custom.OdorID(iTrial) == 1
    LeftPokeAction = 'rewarded_Lin';
    RightPokeAction = 'unrewarded_Rin';
elseif BpodSystem.Data.Custom.OdorID(iTrial) == 2
    LeftPokeAction = 'unrewarded_Lin';
    RightPokeAction = 'rewarded_Rin';
else
    error('Bpod:Olf2AFC:unknownOdorID','Undefined Odor ID')
end

sma = NewStateMatrix();
sma = SetGlobalTimer(sma,1,TaskParameters.GUI.FeedbackDelay);
sma = AddState(sma, 'Name', 'wait_Cin',...
    'Timer', 0,...
    'StateChangeConditions', {'Port2In', 'stay_Cin'},...
    'OutputActions', {'SoftCode',2,'PWM2',255});
sma = AddState(sma, 'Name', 'stay_Cin',...
    'Timer', TaskParameters.GUI.StimDelay,...
    'StateChangeConditions', {'Port2Out','broke_fixation','Tup', 'odor_delivery'},...
    'OutputActions',{});
sma = AddState(sma, 'Name', 'broke_fixation',...
    'Timer',0,...
    'StateChangeConditions',{'Tup','timeOut_BrokeFixation'},...
    'OutputActions',{});
% sma = AddState(sma, 'Name', 'pre_odor_delivery',...
%     'Timer', 0.1,... % Time for odor to reach nostrils (Junya filtered these trials out offline)
%     'StateChangeConditions', {'Port2Out','ITI','Tup','odor_delivery'},...
%     'OutputActions', {'SoftCode',BpodSystem.Data.Custom.OdorPair(iTrial)});
sma = AddState(sma, 'Name', 'odor_delivery',...
    'Timer', 0,...
    'StateChangeConditions', {'Port2Out','wait_Sin'},...
    'OutputActions', {'SoftCode',BpodSystem.Data.Custom.OdorPair(iTrial)});
sma = AddState(sma, 'Name', 'wait_Sin',...
    'Timer',TaskParameters.GUI.ChoiceDeadLine,...
    'StateChangeConditions', {'Port1In','start_Lin','Port3In','start_Rin','Tup','missed_choice'},...
    'OutputActions',{'SoftCode',2,'PWM1',255,'PWM3',255});
sma = AddState(sma, 'Name','start_Lin',...
    'Timer',0,...
    'StateChangeConditions', {'Tup',LeftPokeAction},...
    'OutputActions',{'GlobalTimerTrig',1});
sma = AddState(sma, 'Name','start_Rin',...
    'Timer',0,...
    'StateChangeConditions', {'Tup',RightPokeAction},...
    'OutputActions',{'GlobalTimerTrig',1});
sma = AddState(sma, 'Name', 'rewarded_Lin',...
    'Timer', TaskParameters.GUI.FeedbackDelay,...
    'StateChangeConditions', {'Port1Out','rewarded_Lin_grace','Tup','water_L','GlobalTimer1_End','water_L'},...
    'OutputActions', {});
sma = AddState(sma, 'Name', 'rewarded_Lin_grace',...
    'Timer', TaskParameters.GUI.FeedbackDelayGrace,...
    'StateChangeConditions',{'Tup','skipped_feedback','Port1In','rewarded_Lin','GlobalTimer1_End','skipped_feedback','Port2In','skipped_feedback','Port3In','skipped_feedback'},...
    'OutputActions', {});
sma = AddState(sma, 'Name', 'rewarded_Rin',...
    'Timer', TaskParameters.GUI.FeedbackDelay,...
    'StateChangeConditions', {'Port3Out','rewarded_Rin_grace','Tup','water_R','GlobalTimer1_End','water_R'},...
    'OutputActions', {});
sma = AddState(sma, 'Name', 'rewarded_Rin_grace',...
    'Timer', TaskParameters.GUI.FeedbackDelayGrace,...
    'StateChangeConditions',{'Tup','skipped_feedback','Port3In','rewarded_Rin','GlobalTimer1_End','skipped_feedback','Port2In','skipped_feedback','Port1In','skipped_feedback'},...
    'OutputActions', {});
sma = AddState(sma, 'Name', 'unrewarded_Lin',...
    'Timer', TaskParameters.GUI.FeedbackDelay,...
    'StateChangeConditions', {'Port1Out','unrewarded_Lin_grace','Tup','timeOut_IncorrectChoice','GlobalTimer1_End','timeOut_IncorrectChoice'},...
    'OutputActions', {}); % SHOULD WRITE WAVEFORM TO PULSEPAL WITHIN THIS CODE
sma = AddState(sma, 'Name', 'unrewarded_Lin_grace',...
    'Timer', TaskParameters.GUI.FeedbackDelayGrace,...
    'StateChangeConditions',{'Tup','skipped_feedback','Port1In','unrewarded_Lin','GlobalTimer1_End','skipped_feedback','Port2In','skipped_feedback','Port3In','skipped_feedback'},...
    'OutputActions', {});
sma = AddState(sma, 'Name', 'unrewarded_Rin',...
    'Timer', TaskParameters.GUI.FeedbackDelay,...
    'StateChangeConditions', {'Port3Out','unrewarded_Rin_grace','Tup','timeOut_IncorrectChoice','GlobalTimer1_End','timeOut_IncorrectChoice'},...
    'OutputActions', {});% RATHER THAN PLAYING WHATEVER IS THERE
sma = AddState(sma, 'Name', 'unrewarded_Rin_grace',...
    'Timer', TaskParameters.GUI.FeedbackDelayGrace,...
    'StateChangeConditions',{'Tup','skipped_feedback','Port3In','unrewarded_Rin','GlobalTimer1_End','skipped_feedback','Port2In','skipped_feedback','Port1In','skipped_feedback'},...
    'OutputActions', {});
sma = AddState(sma, 'Name', 'water_L',...
    'Timer', LeftValveTime,...
    'StateChangeConditions', {'Tup','ITI'},...
    'OutputActions', {'ValveState', 1});
sma = AddState(sma, 'Name', 'water_R',...
    'Timer', RightValveTime,...
    'StateChangeConditions', {'Tup','ITI'},...
    'OutputActions', {'ValveState', 4});
sma = AddState(sma, 'Name', 'timeOut_BrokeFixation',...
    'Timer',TaskParameters.GUI.TimeOutBrokeFixation,...
    'StateChangeConditions',{'Tup','ITI'},...
    'OutputActions',{'BNCState',1});
sma = AddState(sma, 'Name', 'timeOut_IncorrectChoice',...
    'Timer',TaskParameters.GUI.TimeOutIncorrectChoice,...
    'StateChangeConditions',{'Tup','ITI'},...
    'OutputActions',{'BNCState',1});
sma = AddState(sma, 'Name', 'timeOut_SkippedFeedback',...
    'Timer',TaskParameters.GUI.TimeOutSkippedFeedback,...
    'StateChangeConditions',{'Tup','ITI'},...
    'OutputActions',{});
sma = AddState(sma, 'Name', 'skipped_feedback',...
    'Timer', 0,...
    'StateChangeConditions', {'Tup','timeOut_SkippedFeedback'},...
    'OutputActions', {});
sma = AddState(sma, 'Name', 'missed_choice',...
    'Timer',0,...
    'StateChangeConditions',{'Tup','ITI'},...
    'OutputActions',{});
sma = AddState(sma, 'Name', 'ITI',...
    'Timer',TaskParameters.GUI.ITI,...
    'StateChangeConditions',{'Tup','exit'},...
    'OutputActions',{'SoftCode',32}); % Sets flow rates for next trial
% sma = AddState(sma, 'Name', 'state_name',...
%     'Timer', 0,...
%     'StateChangeConditions', {},...
%     'OutputActions', {});
end